### ISSUE TITLE
java.lang.NoClassDefFoundError: com.naver.glink.android.sdk.R$drawable

### ISSUE THREAD

**Issue by OrangeWxc** [naver/cafe-sdk-android#2]
Hi,Why have this problem?call function Glink.startHome(zbMainActivity.this);
**java.lang.NoClassDefFoundError: com.naver.glink.android.sdk.R$drawable**

**Comment by wonkuym** [comment]
2016.05.09 월요일
17:40 원겸 경환님, 샘플 게임 아래 repository에서 작업하시면 될 거 같아요~~
17:40 원겸 https://oss.navercorp.com/GLink/UnrealMatch3.git
17:44 조경환 넵~ 고맙습니다
2016.05.11 수요일
17:52 조경환 Remove duplicate android support v4 library in your project.

If did you build in eclipse, please follow the below steps.
1. extract cafeSdk-1.5.0.zip
2. copy into cafeSdk-1.5.0/libs
3. import the project
4. open Propertis > android and Checked Library set Is Library
5. add cafeSdk in your project

if don't you see sample project, you should check sample project

show sample project 
[navercafesdk-sample-eclipse-master](https://github.com/naver/cafe-sdk-android/tree/master/sample/navercafesdk-sample-eclipse-master)

**Comment by OrangeWxc** [comment]
1.download cafe-sdk-android-master.zip
2.inport  cafe-sdk-android-master\sample\navercafesdk-sample-eclipse-master  cafeSdk and cafeSdkSample
3.cafeSdk isLibrary
4.run as android application ,then problem show 

I should extract cafeSdk-1.5.0.zip and copy cafeSdk-1.5.0.jar to cafeSdk/libs,then it's ok

**Comment by OrangeWxc** [comment]
THX
